# server 172.16.100.0 255.255.255.0
verb 3
tls-server
tls-version-min 1.2
auth SHA256
ca /etc/openvpn/easyrsa/pki/ca.crt
key /etc/openvpn/easyrsa/pki/private/server.key
cert /etc/openvpn/easyrsa/pki/issued/server.crt
dh /etc/openvpn/easyrsa/pki/dh.pem
crl-verify /etc/openvpn/easyrsa/pki/crl.pem
tls-crypt /etc/openvpn/easyrsa/pki/ta.key
cipher AES-256-GCM
#management 127.0.0.1 8989
keepalive 10 60
persist-key
persist-tun
topology subnet
#duplicate-cn
#proto tcp
#port 1194
#dev tun0
status /tmp/openvpn-status.log
user nobody
group nogroup
push "topology subnet"
push "route-metric 9999"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
